version: '3.7'
services:
  videcuttool-server:
    container_name: videcuttool-server
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src:ro
      - ./server:/app/server
      - ./public:/app/public
      - /app/node_modules/
      - /app/server/node_modules/
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - FAST_REFRESH=true
      - DB_CONNECTION_URL=postgresql://videocuttool:videocuttool@database:5432/videocuttool
      - BACKEND_URL=http://videcuttool-server:4000/api/
    env_file:
      - .env.dev
    depends_on:
      - database
  database:
    restart: unless-stopped
    image: postgres:15
    ports:
      - "5435:5432/tcp"
    environment:
      POSTGRES_PASSWORD: videocuttool
      POSTGRES_USER: videocuttool
      POSTGRES_DB: videocuttool
      PGDATA: /var/lib/postgresql/data/pg_data
    volumes:
      - ./postgres:/var/lib/postgresql/data
  nginx:
    restart: always
    depends_on:
      - videcuttool-server
    image: nginx:latest
    env_file:
      - .env.dev
    ports:
      - ${BETA_PORT:-8000}:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
volumes:
  exclude:
